### ISSUE TITLE
Scripts to run graph reconstruction tasks

### ISSUE THREAD

**Issue by AdarshMJ** [joeybose/HyperbolicNF#13]
Hi!
I was wondering if you could point me to the scripts to recreate the results for the graph reconstruction tasks on disease I and II datasets reported in table 3 of your paper.  Is it run_diseases_wrapped_flow_sweep.sh for the WHC version?

Thanks in advance!

**Comment by joeybose** [comment]
Hi, I believe that is the script. Basically if you pass in the argument: --flow_model='WrappedRealNVP' it will use WHC.
